name:                HSoM-Exercises
version:             0.1.0.0
github:              "sackyhack/HSoM-Exercises"
license:             BSD3
author:              "Craig Ferguson"
maintainer:          "sackyhack@tworing.ca"
copyright:           "2021 Craig Ferguson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sackyhack/HSoM-Exercises#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - Euterpea
  - HSoM

executables:
  HSoM-Exercises-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HSoM-Exercises

tests:
  HSoM-Exercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HSoM-Exercises
